server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://120.55.68.139:3306/haders?serverTimezone=Asia/Shanghai
    username: root
    password: 5)fs9%rfF>Ko!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #自动生成数据库表（关键）
#      ddl-auto: none
      #jpa配置：在控制台显示Hibernate的sql(可选)
#    show-sql: false





